# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2c9ef02cefe93fdbc8e3a3451a16b24dfdcf48e002f9538dece3da507a44d4135a83b264b31c462603beefa55ab6e4740f6eb51269c0ac8ee744f1827206001

test:
  secret_key_base: 959fac9e8c3bd92a7814f63c4a5e63e63d958648933095dd57489ce531dbd33f8050f6c9320b7cbb8f08e38ace5d265aa1cf29387112f5cd448af289150a49b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
